default_platform(:ios)

KEYCHAIN_NAME = ENV['TEMP_KEYCHAIN_NAME']
KEYCHAIN_PASSWORD = ENV['TEMP_KEYCHAIN_PASSWORD']
GIT_BASIC_AUTHORIZATION = ENV['MATCH_GIT_BASIC_AUTHORIZATION']
ISSUER_ID = ENV['API_ISSUER_ID']
KEY_ID = ENV['API_KEY_ID']
KEY_CONTENT = ENV['API_KEY_CONTENT']

# Keychain 관련 메소드
def delete_temp_keychain(name)
  delete_keychain(name: name) if File.exist?(File.expand_path("~/Library/Keychains/#{name}-db"))
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

# Fastfile 설정 시작
platform :ios do

  # 코드 서명을 위한 private lane 정의
  private_lane :code_signing do
    match(
      type: "appstore",
      readonly: true,
      git_basic_authorization: ENV['GIT_BASIC_AUTHORIZATION'],
      keychain_name: ENV['KEYCHAIN_NAME'],
      keychain_password: ENV['KEYCHAIN_PASSWORD']
    )
  end

  # API 키를 가져오는 private lane 정의
  private_lane :get_api_key do
    app_store_connect_api_key(
      key_id: ENV['KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['KEY_CONTENT'],
      duration: 1200, # 토큰 유효 시간 (초 단위)
      in_house: false # 사설 배포 여부 (true로 설정 시 내부 배포로 간주)
    )
  end

  # 빌드 번호를 증가시키는 private lane 정의
  private_lane :bump_build_number do |options|
    api_key = options[:api_key]

    version = get_version_number(
      xcodeproj: "RaiseMeUp.xcodeproj",
      target: "RaiseMeUp-PROD"
    )
    puts "Version : #{version}"

    latest_build_number = latest_testflight_build_number(
      api_key: api_key,
      version: version,
      initial_build_number: 0
    )
    puts "Latest build number : #{latest_build_number}"

    increment_build_number(
      build_number: latest_build_number + 1,
      xcodeproj: "RaiseMeUp.xcodeproj"
    )
  end

  # TestFlight에 앱을 배포하는 lane 정의
  desc "Distribute app to TestFlight"
  lane :distribute_testflight do
    ensure_temp_keychain(ENV['KEYCHAIN_NAME'], ENV['KEYCHAIN_PASSWORD'])

    code_signing

    api_key = get_api_key

    bump_build_number(api_key: api_key)

    build_app(
      workspace: "RaiseMeUp.xcworkspace",
      scheme: "RaiseMeUp-PROD",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "build_output",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "./build_output/RaiseMeUp-PROD.ipa",
      skip_waiting_for_build_processing: true
    )

    delete_temp_keychain(ENV['KEYCHAIN_NAME'])
  end

end


# ...
