//
//  ExerciseCounterRouter.swift
//  RaiseMeUp
//
//  Created by 홍석현 on 12/14/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Shared

protocol ExerciseCounterRoutingLogic {
    func dismiss()
}

protocol ExerciseCounterDataPassing
{
    var dataStore: ExerciseCounterDataStore? { get }
}

class ExerciseCounterRouter: NSObject, ExerciseCounterRoutingLogic, ExerciseCounterDataPassing, ExerciseCounterCoordinatorProtocol
{
    
    weak var viewController: ExerciseCounterViewController?
    var dataStore: ExerciseCounterDataStore?
    
    var navigationController: UINavigationController
    
    var finishDelegate: CoordinatorFinishDelegate?
    
    var childCoordinators: [Coordinator] = []
    
    var type: CoordinatorType { .exerciseCounter }
    private var routine: [Int]
    
    init(
        navigationController: UINavigationController,
        routine: [Int]
    ) {
        self.navigationController = navigationController
        self.routine = routine
    }
    
    func start() {
        let viewController = ExerciseCounterViewController()
        let router = self
        viewController.router = self
        dataStore?.routine = router.routine
        router.viewController = viewController
        router.dataStore = viewController.interactor
        viewController.interactor?.routine = routine
        
        self.navigationController.pushViewController(viewController, animated: true)
    }
    
    func finish() {
        self.finishDelegate?.coordinatorDidFinish(childCoordinator: self)
    }
    
    func dismiss() {
        finish()
    }
}
