//
//  ExerciseCounterPresenter.swift
//  RaiseMeUp
//
//  Created by 홍석현 on 12/14/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExerciseCounterPresentationLogic
{
  func presentSomething(response: ExerciseCounter.Something.Response)
}

class ExerciseCounterPresenter: ExerciseCounterPresentationLogic
{
  weak var viewController: ExerciseCounterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ExerciseCounter.Something.Response)
  {
    let viewModel = ExerciseCounter.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
