//
//  ExerciseCounterInteractor.swift
//  RaiseMeUp
//
//  Created by 홍석현 on 12/14/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExerciseCounterBusinessLogic {
    func pullNextRep(request: ExerciseCounter.CountRep.Request)
    func startButtonTapped()
    func countOnePullUp()
}

protocol ExerciseCounterDataStore {
    var routine: [Int] { get set }
}

class ExerciseCounterInteractor: ExerciseCounterBusinessLogic, ExerciseCounterDataStore {
    var routine: [Int] = [] 
    
    var presenter: ExerciseCounterPresentationLogic?
    var worker: ExerciseCounterWorker?
    // MARK: Do something
    private var currentRep: Int = 0
    
    func pullNextRep(request: ExerciseCounter.CountRep.Request) {
        currentRep = routine.removeFirst()
        let response = ExerciseCounter.CountRep.Response(currentRep: currentRep)
        presenter?.presentCurrentRep(response: response)
    }
    
    func startButtonTapped() {
        currentRep = routine.removeFirst()
        let response = ExerciseCounter.CountRep.Response(currentRep: currentRep)
        presenter?.presentCurrentRep(response: response)
    }
    
    func countOnePullUp() {
        currentRep -= 1
        if currentRep <= 0 {
            pullNextRep(request: ExerciseCounter.CountRep.Request())
        }
        let response = ExerciseCounter.CountRep.Response(currentRep: currentRep)
        presenter?.presentCurrentRep(response: response)
    }
}
